### ISSUE TITLE
Which encode type do you use for huawei flavor type?

### ISSUE THREAD

**Issue by burxtx** [huaweicloud/trace_generation_rnn#1]
Hi,

I'm appreciated you writing this paper and public the code. 
I have a question, for the azure data, the flavors are encoded using alphabetic characters. How do you encode the huaweicloud flavor I noticed there are 256 you mentioned in your paper. 
Thanks a lot~

**Comment by sbergsma** [comment]
Hi Xi Tian, thanks for your interest!

FYI, you can see we have a [`flap_map.txt` file](https://github.com/huaweicloud/trace_generation_rnn/blob/main/resources/maps/flav_map.txt) that defines the encoding.  There were so few Azure flavors, we mapped them to a small set of alphabetic characters as you noted.  For other datasets, like huaweicloud, we often just use the original flavor names.  So in `flav_map.txt`, rather than pairs like `1,0.75 a`, we will just have like `s6.2xlarge.2 s6.2xlarge.2`.  Then in the trace file, we will have lines like `s6.xlarge.2,s6.xlarge.2,s6.xlarge.2,s6.xlarge.2,s6.xlarge.2,s6.xlarge.2,s6.xlarge.2,s6.xlarge.2,s6.large.4,s6.large.2,c3.large.2, ...`.

For visualizing with colors, we create a mapping from the flavor codes to colors, sampling colors from with the standard `matplotlib` color maps.  We don't rely on the codes being single alphabetic characters.

**Comment by burxtx** [comment]
Very clear! Thank you for your reply.
